### ISSUE TITLE
Missing folder : vendor

### ISSUE THREAD

**Issue by TavernierAlicia** [biplobice/CakeShop#2]
Hi,
I followed your instructions but I still got these errors :

`Warning: require(C:\wamp64\www\CakeShop\vendor\autoload.php): failed to open stream: No such file or directory in C:\wamp64\www\CakeShop\config\bootstrap.php on line 23`

`Fatal error: require(): Failed opening required 'C:\wamp64\www\CakeShop\vendor\autoload.php' (include_path='.;C:\php\pear') in C:\wamp64\www\CakeShop\config\bootstrap.php on line 23`

It seems like the folder 'vendor' is missing.
Thanks !

**Comment by biplobice** [comment]
Hi @TavernierAlicia 
Thanks for your interest in this project.

- Please open your terminal/CLI and follow the following steps-

```
cd YOUR_WWW_DIR
git clone git@github.com:biplobice/CakeShop.git
cd CakeShop
composer install
```
- Import the MySQL file.
- Open `CakeShop/config/app.php`. Update your database info
Now, view on your browser.

**Comment by biplobice** [comment]
I'm assuming the above comment worked for you and closing the issue.
