### ISSUE TITLE
Impossible to generate condition with empty list of values for field (request_id)

### ISSUE THREAD

**Issue by zukol21** [biplobice/CakeShop#3]
Hi,
i just installed the app, but i'm having a problem with getting it to work. 
The browser returns error: Impossible to generate condition with empty list of values for field (request_id), which i suppose means that there is a compatibility issue with cakePhp. The one I have installed is 3.7.6. Do you have any advice?

**Comment by zukol21** [comment]
ok so 3.7.5 seems to make it work, the main page shows up, but the admin page is blank...

**Comment by biplobice** [comment]
Hi @zukol21 Thanks for your information. I'll check the issue ASAP.

**Comment by biplobice** [comment]
@zukol21 
I've checked it on my local, working fine.
There was some deprecated warnings. I've fixed those. Though it's not related with this issue but please check with the latest commit.
If it doesn't work for you, please send me a bit more information about the error.
Thanks.

**Comment by biplobice** [comment]
Closing due to lack of information.
